<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/* upgrade changes */
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory');
$customerSession = $customerSession->create();
$customHelper = $this->helper('Ntz\Productpage\Helper\Data');
$groupName = $customHelper->getCustomerGroupName();
$productMsrp = $customHelper->getProduct();
$msrp ="";
if ($productMsrp){
    $msrp = $productMsrp->getMsrp();
}
$priceArapper = "";
$vatPrice="";
if($customerSession->isLoggedIn()) {
    if($groupName!='NOPRICE'){
    $label = __('NET:');
    $price = $block->getPriceType('tier_price');
    $tier_price_amt = $price->getAmount()->getBaseAmount();
    if(isset($price) && ($tier_price_amt!="" || $tier_price_amt!=0)) {
        $customer = $customerSession->getCustomer();
        $customerGroupId = $customer['group_id'];
        $groupname = $objectManager->create('\Magento\Customer\Api\GroupRepositoryInterface')-> getById($customerGroupId)->getCode();
        $group_4ML = array("4MLDNET","4MLNOVAT","4MLRRP","4MLTELT","4MLWHSL");
        if(in_array($groupname, $group_4ML)) {
            $label = __('RRP:');
            $vatPrice = 'vat_rrp_class';
        }

        if($msrp != $price->getAmount()){
        ?>
            <?= $priceArapper =  /* @noEscape */ $block->renderAmount($price->getAmount(), ["vat_rrp_class"   => $vatPrice,"final_price_amount"   => 'final_price_amount',"display_label"   => $label,"price_id"        => $block->getPriceId("product-price-" . $idSuffix),"price_type"        => "finalPrice","include_container" => true,"schema" => $schema]); ?>
        <?php
        }
    }
    }
} ?>


<?php
if ($block->showMinimalPrice()) :
    if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif;
endif;
