<?php
$helper = $this->helper('Ntz\Productpage\Helper\Data');
$baseUrl = $helper->getBaseUrl();

?>
<div class="title-wrap">
<div class="container">
<div class="page-titles">
<h1 class="wishlist">My Portfolio</h1>
</div>
<div class="breadcrumb-container col-sm-4 col-lg-5">
<ul class="breadcrumb">
<li class="Home">
<a href="/" title="Home">Home</a>
</li>
<li class="Portfolio">
<strong>Portfolio</strong>
</li>
</ul>
</div>
</div>
</div>
