<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<!--<div class="container-fluid container-account-title">
<div class="page-title col-sm-12 col-lg-12 text-center">
<h1><?php echo __('Reset / Forgot Your Password?') ?></h1>
</div>
</div>-->
<div class="container-fluid user-forms">
	<div class="row">
		<div class="user-form-wrap col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
			<div class="inner">
				<div class="content">
					<h2><?= $block->escapeHtml(__('Forgot Password')) ?></h2>
					<p><?= $block->escapeHtml(__('Please enter your email address below. You will receive a link to reset your password.')) ?></p>
					<form class="form password forget"
						  action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
						  method="post"
						  id="form-validate"
						  data-mage-init='{"validation":{}}'>
						<fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
							<div class="field email required">
								<label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
								<div class="control">
									<input type="email" placeholder="Email Address" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
								</div>
							</div>
							<?= $block->getChildHtml('form_additional_info') ?>
						</fieldset>
						<div class="actions-toolbar">
							<div class="primary">
								<a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('&#171; Back to Login')) ?></span></a>
							</div>
							<div class="secondary">
							<button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>	
