<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>


<div class="container-fluid account-login">
<div class="row">
	<div class="block-customer-login bb registered-users col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
		<div class="inner">
			<div class="content">
				<h2 id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Log In')) ?></h2>
				<p><?= $block->escapeHtml(__('Already have an Arteriors account? Log in below.')) ?></p>
				<div class="login-main block-content" aria-labelledby="block-customer-login-heading">
					<form class="form form-login"
						  action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
						  method="post"
						  id="login-form"
						  data-mage-init='{"validation":{}}'>
						<?= $block->getBlockHtml('formkey') ?>
						<div class="row field login-fields">
							<div class="email required col-md-12">
								<label for="email_address" class="label">Email Address</label>
								<div class="control">
									<input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" placeholder="Email Address" maxlength="80" class="input-text v-validate" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}'  data-validate="{required:true}">
								</div>
							</div>
							<div class="password required col-md-12">
								<label for="password" class="label">Password</label>
								<div class="control">
									<input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> placeholder="Password" autocomplete="off"<?php endif; ?> class="input-text v-validate" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" maxlength="20" data-validate="{required:true}">
								</div>
							</div>
						</div>
						<?= $block->getChildHtml('form_additional_info') ?>
						<div class="row">
							<div class="col-md-12">
								<div class="actions-toolbar">
									<div class="primary">
										<button type="submit" class="action login primary login-btn-dflt" name="send" id="send2"><span><?= $block->escapeHtml(__('LOG IN')) ?></span></button>
									</div>
									<div class="secondary">
										<a class="action remind frgt-pswd-btn" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Reset Password')) ?></span></a>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								
									
									<div class="secondary">
										<p> <?= $block->escapeHtml(__('Don\'t Have An Account?')) ?> 
										<a class="action create-new-account" href="<?= $this->getUrl('registration/account/create') ?>">
											<span><?= $block->escapeHtml(__('Create Account')) ?></span>
										</a>
										</p> 
									</div>
									
								
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>



