<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
/* upgrade changes */
?>
<!--<div class="container-fluid container-account-title">
  <div class="page-title col-sm-12 col-lg-12 text-center">
    <h1><?php echo __('Reset Your Password?') ?></h1>
  </div>
</div>-->
<div class="container-fluid user-forms">
	<div class="row">
		<div class="user-form-wrap col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
			<div class="inner">
				<div class="content">
					<h2><?= $block->escapeHtml(__('Reset Password')) ?></h2>
					<p><?= $block->escapeHtml(__('Please enter your new password below.')) ?></p>
					  <form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['id'=>$block->getRpCustomerId(), 'token' => $block->getResetPasswordLinkToken()]])) ?>"
							method="post"
							  <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
							id="form-validate"
							class="form password reset"
							data-mage-init='{"validation":{}}'>
							<div class="fieldset" class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
							  
							<div class="row field">
								<div class="password required col-md-12">
									<label for="password" class="required"><?php echo __('New Password') ?></label>
									<div class="control">
										<input type="password" class="input-text required-entry validate-password" name="password" id="password"
											 data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
											 data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
											 data-validate="{required:true, 'validate-customer-password':true}"
											 autocomplete="off" placeholder="New Password">
									</div>
								</div>
								<div class="confirmation required col-md-12">
									<label for="confirmation" class="required"><?php echo __('Confirm New Password') ?></label>
									<div class="control">
										<input type="password" class="input-text required-entry validate-cpassword" name="password_confirmation" id="password-confirmation"  data-validate="{required:true,equalTo:'#password'}" autocomplete="off" placeholder="Confirm New Password">
									</div>
								</div>
							</div>

							 
						  </div>
						  <!--<p class="required">* <?php echo __('Required Fields') ?></p>-->
						  <div class="buttons-set">
							 <button type="submit" title="Reset a Password" class="button submit primary"><span><span><?= $block->escapeHtml(__('Reset a Password')) ?></span></span></button>
						  </div>
					   </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>	