<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage\Link */

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore()->getBaseUrl();

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
$portfolio = $objectManager->get("Magento\Checkout\Block\Cart\Grid");
$portfolio->getChildHtml('form_before');
$customHelper = $objectManager->get('Ntz\Productpage\Helper\Data');
$groupname = $customHelper->getCustomerGroupName();


$restrictCheckout = $objectManager->get('Ntz\Arteriors\Helper\GetRestrictCheckout');
$restrictedCountry = $restrictCheckout->getRestricted();


$group_4ML = array("4MLDNET","4MLRRP","4MLWASL","4MLNOVAT","4MLTELT","4MLWHSL");
?>
<?php if ($portfolio->getContinueShoppingUrl()) :?>
	<!-- <li class="item">
		<a class="button btn-continue"
		   href="<?= $block->escapeUrl($portfolio->getContinueShoppingUrl()) ?>"
		   title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
			<span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
		</a>
	</li> -->
 <?php endif; ?>
<?php if ($restrictedCountry != 1) { ?>

<?php if (!in_array($groupname, $group_4ML) ): ?>
    <li>
    <?php if ($block->isPossibleOnepageCheckout()): ?>
        <a type="button"
                href="<?php echo $store; ?>checkout"
                title="<?= $block->escapeHtmlAttr(__('PROCEED TO CHECKOUT')) ?>"
				role="button"
				tabindex="0"
				aria-label="PROCEED TO CHECKOUT"
                class="button btn-proceed-checkout btn-checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
                <?php if ($block->isDisabled()) :?>
                    disabled="disabled"
                <?php endif; ?>>
            <span><?= $block->escapeHtml(__('PROCEED TO CHECKOUT')) ?></span>
        </a>
        
    <?php endif; ?>
    </li>
<?php endif;
 
} ?>