<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="category-page">
    <div class="container-fluid">
        <div class="page-title category-title col-sm-8 col-lg-5">
			<?php echo $block->getChildHtml('page.main.title');?>
		</div>
		
		
		<div class="category-breadcrumbs col-sm-4 col-lg-5">
    <ul class="breadcrumb">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="<?= $block->escapeHtmlAttr($crumbName) ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                   title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                </a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>


</div></div>
<?php endif; ?>
