<?php
$createUrl = $this->getUrl('customer/account/create');
$loginUrl = 'customer/account/login';
$currentUrl = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); 
if (strpos($currentUrl, $loginUrl) !== false):
?>
    <div class="container-fluid container-account-title">
        <div class="page-title category-title col-sm-8 col-lg-5">
            <h1><?php echo __('Sign In') ?></h1>
        </div>
    </div>
<?php elseif($currentUrl == $createUrl): ?>
    <div class="container-fluid container-account-title">
        <div class="page-title category-title col-sm-8 col-lg-5">
            <h1><?php echo __('Sign Up') ?></h1>
        </div>
        <div class="category-breadcrumbs col-sm-4 col-lg-5">
            <ul class="breadcrumb">
                <li class="Home">
                    <a href="/" title="Home"><?php echo __('Home') ?></a>
                </li>
                <li class="Sign-Up">
                    <strong><?php echo __('Sign-Up') ?></strong>
                </li>
            </ul>
        </div>
    </div>
<?php endif;