<div class="bg-overlay company_user_section">
    <!--Creates the popup body-->
    <div class="popup-overlay">
        <!--Creates the popup content-->
        <div class="popup-content">
            <div class="dynamic_pop_content">
                <h4>Confirm Email Address</h4>
                <p class="validate_text"></p>
                <button class="primary button_validate" type="button" data-value="1"><span>Yes</span></button>
                <button class="primary button_validate" type="button" data-value="0"><span>No</span></button>
            </div>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        $(document).on('click', '.company-users-index button.primary, .company-users-index a.action', function (e) {
            $("footer button.save").attr("disabled",false);
        });
    });

</script>
