<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
/**
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div><a itemprop="brand" itemscope itemtype="http://schema.org/Brand" class="logo" href="<?= $block->escapeUrl($block->getUrl('')) ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <img itemprop="logo" src="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
</a>
</div>
