<?php
    /** @var Klevu\FrontendJs\Block\Html\Head\JsInit $block */
?>
<script type="text/javascript" id="klevu_jsinteractive">
	klevu({
        powerUp: {
            quick: false,
            "recsModule": true,
            landing: false,
            catnav:false
        }
    });
    klevu.interactive(function () {
        var options = <?php /** @noEscape */ echo $block->getInteractiveOptionsSerialized(); ?>;
        <?php /** @noEscape */ echo $block->getChildHtml('additional_before'); ?>
        klevu(options);
        <?php /** @noEscape */ echo $block->getChildHtml('additional_after'); ?>
    });
</script>