<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseUrl =  $storeManager->getStore()->getBaseUrl();


?>
<?php if ($this->helper(\Magento\Cookie\Helper\Cookie::class)->isCookieRestrictionModeEnabled()) : ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block"
         style="display: none;">
        
		<div role="document" class="content" tabindex="0">
			<div class="cookie-logo">
				<img src="<?php echo $baseUrl; ?>media/logo/stores/1/logo-cookie.png" alt="Arteriors | Inspired Furnishings">
			</div>
			<div class="cookie-content">
				<p><?= $block->escapeHtml(__('This website uses cookies')) ?></p>
				<p><?= $block->escapeHtml(__('The types of cookies we use, and the way we use them, are explained in our')) ?>
                 <a href="<?php echo $baseUrl; ?>privacy-policy">Privacy Policy</a>
                <?= $block->escapeHtml(__(' By clicking "Accept", or continuing to browse this site, you agree to our use of cookies.')) ?>
				</p>
				<div class="actions">
					<button id="btn-cookie-allow" class="action allow primary">
						<span><?= $block->escapeHtml(__('Allow Cookies')) ?></span>
					</button>
				</div>
			</div>
        </div>
    </div>
	
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
