<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Send to friend form
 */
/** @var \Magento\SendFriend\Block\Send $block */

?>
<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button" id="btn-remove<%- data._index_ %>" class="action remove"
               title="<?= $block->escapeHtmlAttr(__('Remove Recipent')) ?>">
              <img src="https://static.arteriorshome.com/skin/frontend/arteriorshome/default/images/btn_remove.gif" alt="Remove Recipent">
            </button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field name required">
            <label for="recipients-name<%- data._index_ %>" class="label"><span><?= $block->escapeHtml(__('Name:')) ?></span></label>
            <div class="control">
                <input name="recipients[name][<%- data._index_ %>]" type="text" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" class="input-text"
                       id="recipients-name<%- data._index_ %>" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label for="recipients-email<%- data._index_ %>" class="label"><span><?= $block->escapeHtml(__('Email Address:')) ?></span></label>
            <div class="control">
                <input name="recipients[email][<%- data._index_ %>]" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       id="recipients-email<%- data._index_ %>" type="email" class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </fieldset>
</script>
<div class ="send-form-text"><h1>Email to a Friend</h1></div>
<form action="<?= $block->escapeUrl($block->getSendUrl()) ?>" method="post" id="product-sendtofriend-form"
      data-mage-init='{
        "rowBuilder":{
            "rowTemplate":"#add-recipient-tmpl",
            "rowContainer":"#recipients-options",
            "rowParentElem":"<div></div>",
            "remEventSelector":"button",
            "btnRemoveSelector":".action.remove",
            "maxRows":"<?= /* @noEscape */ (int)$block->getMaxRecipients() ?>",
            "maxRowsMsg":"#max-recipient-message",
            "addRowBtn":"#add-recipient-button",
            "additionalRowClass":"additional"},
        "validation":{}}'
      class="form send friend" data-hasRequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset sender" id="sender_options">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Sender:')) ?></span></legend>
        <div class="main_sender_box">
        <div class="field sender required">
            <label for="sender-name" class="label"><span><?= $block->escapeHtml(__('Name:')) ?></span><em></em></label>
            <div class="control">
                <input name="sender[name]" value="<?= $block->escapeHtmlAttr($block->getUserName()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>" id="sender-name" type="text" class="input-text"
                       data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label for="sender-email" class="label"><span><?= $block->escapeHtml(__('Email:')) ?></span><em></em></label>
            <div class="control">
                <input name="sender[email]" value="<?= $block->escapeHtmlAttr($block->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>" id="sender-email" type="email" class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field text required">
            <label for="sender-message" class="label"><span><?= $block->escapeHtml(__('Message:')) ?><em></em></span></label>
            <div class="control">
                <textarea name="sender[message]" class="input-text" id="sender-message" cols="3" rows="3"
                          data-validate="{required:true}"><?= $block->escapeHtml($block->getMessage()) ?></textarea>
            </div>
        </div>
        </div>
    </fieldset>

    <fieldset class="fieldset recipients">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Recipient:')) ?></span></legend>
        <br />
        <div id="recipients-options"></div>
        <?php if ($block->getMaxRecipients()) : ?>
            <div id="max-recipient-message" style="display: none;" class="message notice limit" role="alert">
                <span><?= $block->escapeHtml(__('Maximum %1 email addresses allowed.', $block->getMaxRecipients())) ?></span>
            </div>
        <?php endif; ?>

        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <?= $block->getChildHtml('captcha'); ?>
    <div class="buttons-set form-buttons">
        <p class="back-link">
        <span id="max_recipient_message" style="display:none;">
        Maximum 10 email addresses allowed. </span>&nbsp;
        </p>
        <button type="submit"  class="button"<?php if (!$block->canSend()) : ?> disabled="disabled"<?php endif ?>><span><?= $block->escapeHtml(__('Send Email')) ?></span></button>
        <?php if (1 < $block->getMaxRecipients()) : ?>
                <button type="button" id="add-recipient-button" class="button add">
                    <span><?= $block->escapeHtml(__('Add Recipient')) ?></span></button>
            <?php endif; ?>

    </div>
    <p class="required">* Required Fields</p>

</form>

<script type="text/x-magento-init">
    {
        "a[role='back']": {
            "Magento_SendFriend/js/back-event": {}
        }
    }
</script>

<script>
    require(['jquery'], function($){
        jQuery(document).ready( function() {
                jQuery(".input-text").keyup(function(e){
                    jQuery(this).valid();
                });
        });
        $(document).on( "keyup", ".input-text", function(){
            jQuery(this).valid();
        });
    });
</script>