<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */

$customHelper = $this->helper('Ntz\Productpage\Helper\Data');

?>


<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="action action-delete"
   data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'>
    <span>
    	
        <?= $block->escapeHtml(__('Remove item')) ?>
    </span>
</a>
