<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<div class="custom-msg">
	<span>*Additional Taxes and Fees May Apply</span>
</div>
<?php 
$holidayHours = $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('holiday_hours')
          ->toHtml();
if ($holidayHours){
  echo "<div class='holiday_hours' style='display:block;'>". $holidayHours ."</div>";
} 
?>