<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */

$customHelper = $this->helper('Ntz\Productpage\Helper\Data');
$groupname = $customHelper->getCustomerGroupName();
?>
<?php if (!$block->hasError()) :?>
	<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
	
		<ul class="checkout methods items checkout-methods-items checkout-types">
			<?php foreach ($methods as $method) :?>
				<?php $methodHtml = $block->getMethodHtml($method); ?>
				<?php if (trim($methodHtml) !== '') :?>
					<li><?= /* @noEscape */ $methodHtml ?></li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ul>
	
<?php endif; ?>
	