<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Share\Email\Items $block */
?>
<?php
$imageHelper = $this->helper('\Magento\Catalog\Helper\Image');
$l = $block->getWishlistItemsCount() 
?>
<div>
    <table>
        <tr>
            <?php $i = 0;
            foreach ($block->getWishlistItems() as $item): $i++ ?>
            <?php /* @var \Magento\Wishlist\Model\Item $item */ ?>
            <?php /* @var \Magento\Catalog\Model\Product $_product */ ?>
            <?php
                $_product = $item->getProduct();
                $url = $imageHelper->init($_product, 'product_small_image')
                    ->setImageFile($_product->getSmallImage())
                    ->resize(165)
                    ->getUrl();
                if ($url==""){
                    $url = $block->getImageUrl();
                }
            ?>
            <td class="col product">
                <p>
                    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                        <img src="<?= $url ?>" width="135" height="135" alt="" >
                    </a>
                </p>

                <p>
                    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                        <strong><?= $block->escapeHtml($_product->getName()) ?></strong>
                    </a>
                </p>
                <?php if ($block->hasDescription($item)): ?>
                    <p>
                        <strong><?= $block->escapeHtml(__('Comment')) ?>:</strong>
                        <br/><?= /* @noEscape */  $block->getEscapedDescription($item) ?>
                    </p>
                <?php endif; ?>
                <p>
                    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>">
                        <?= $block->escapeHtml(__('View Product')) ?>
                    </a>
                </p>
            </td>
            <?php if ($i % 3 != 0): ?>
                <td></td>
            <?php else: ?>
        </tr>
        <tr>
            <td colspan="5">&nbsp;</td>
        </tr>
        <?php if ($i < $l): ?>
        <tr>
            <?php endif ?>
            <?php endif ?>
            <?php endforeach ?>
    </table>
</div>
