<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\CustomerCustomAttributes\Block\Form $block */
?>
<?php 

$currentUrl = $block->getRequest()->getUriString();
$changepassword = $block->getUrl('customer/account/edit/changepass/1/');
$editurl = $block->getUrl('customer/account/edit');
$helper = $this->helper('Ntz\Productpage\Helper\Data');
$baseUrl = $helper->getBaseUrl();
$customerSession = $helper->getCustomerSession();

$myword = 'changepass';

$postion = strpos($currentUrl,$myword); 


?>
<form class="form form-edit-account" action="<?= /* @noEscape */ $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>
        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
        <div class="field field-name-email required mm">
             <label class="label" for="email"><span><?= $block->escapeHtml(__('Email Address')) ?></span></label>
            <div class="control">
                <input readonly = "" type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) :
                ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
        
            <fieldset class="fieldset password" data-container="change-email-password">
        <!-- <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" autocomplete="email" name="email" id="email" data-input="change-email" value="<?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div> -->
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
         <div class="  row">
        <div class=" col-md-6">
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div><div class=" col-md-6">
        <div class="field confirm password required confirm-pass" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
            <div for="password-confirmation"  class="confirm-mage mage-error" id="password-confirmation-error" style="display: none;">Please make sure your passwords match</div>
        </div>
    </div>
</div>
        <!-- <?= $block->getChildHtml('form_additional_info') ?> -->
    </fieldset>
        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
         <?php if($currentUrl !== $changepassword):?>
    <div class="row">
    <div class="fieldset col-sm-12" id="trade-off">
    <h2 class="legend">Trade Info</h2>
        <?php if ($userDefinedAttributes) :?>
            <?php $userDefinedAttributes->setEntityType('customer')->setShowContainer(false);?>
            <?php $block->restoreSessionData($userDefinedAttributes->getMetadataForm());?>
            <?= $userDefinedAttributes->toHtml() ?>
        <?php endif;?>
<?php
$uploadfile = $customerSession->getCustomer()->getUploadForCert();
$samplefile = $customerSession->getCustomer()->getSampleCertFile();

?>
<?php if($samplefile == '' && $uploadfile == '' ): ?>
  <a href="https://www.arteriorshome.com/attached/attachment/download/customer/23182/file/L24vYS9uYXZfd3NkbC50eHQ,/">
        <img alt="Download File" title="Download File" src="https://static.arteriorshome.com/skin/frontend/base/default/images/fam_bullet_disk.gif" class="v-middle"></a>
        <div class="custom-checkbox-text">
       <input type="checkbox" id="upload_for_cert_delete_file" name="upload_for_cert_delete_file_delete" value="/n/a/nav_wsdl.txt"><label class="label" for="change-password"> <?php echo __('Delete File') ?>
        </div>
<?php endif; ?>
<?php if($uploadfile): ?>
    <?php $filename = substr($uploadfile, strrpos($uploadfile, '/') + 1); ?>
        <img alt="Download File" title="Download File" src="https://static.arteriorshome.com/skin/frontend/base/default/images/fam_bullet_disk.gif" class="v-middle"><span class="filename"><?php echo $filename; ?> </span>
        <div class="custom-checkbox-text">
      <input type="checkbox" id="upload_for_cert_delete_file" name="upload_for_cert_delete_file_delete" value="<?php echo $uploadfile; ?>"> <?php echo __('Delete File') ?>
        </div>
        

<?php  endif; ?>
       
    </div>
</div>
        <?php endif; ?> 
    </fieldset>

    <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>


    <div class="actions-toolbar">
        <p class="required">* <?php echo __('Required Fields') ?></p>
        <p class="back-link"><a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><small>« </small><?= $block->escapeHtml(__('Back')) ?></a></p>
       <button type="submit" class="action save button" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs(__('Change Email')) ?>",
                "titleChangePassword": "<?= $block->escapeJs(__('Change Password')) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs(__('Change Email and Password')) ?>"
            }
        },  
        "*": {
            "Magento_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($userDefinedAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $userDefinedAttributes->hasUserDefinedAttributes() ?>,
                "mixins": [
                    "Magento_CustomerCustomAttributes/error-placement",
                    "Magento_CustomerCustomAttributes/validation-ignore"
                ]
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<?php if($currentUrl !== $changepassword || $currentUrl !== $editurl){?>
<script type="text/javascript">
    require(['jquery'],function($){
        $(".fieldset.company").hide();
        $(".fieldset.job_title").hide();
       
    });
</script>
<?php } ?>
<?php if($postion != ''){?>
<script type="text/javascript">
    require(['jquery'],function($){
        $("#trade-off").hide(); 
    });
</script>
<?php } ?>

<script>// <![CDATA[
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            
          
          $('#password-confirmation').on('change', function () {
            var newPassowrd = $('#password').val();
          var confirmPassword = $('#password-confirmation').val();
                        if(newPassowrd != confirmPassword){
                       
                        $('.confirm-mage').show();
                        } 
                        if(newPassowrd == confirmPassword){
                        // $('.mage-error').html('Please make sure your passwords match');
                        $('.confirm-mage').hide();
                        } 
                });

        });
        // ]]>
</script>