<?php
$blockHtml = $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('megamenu-refresh')
    ->toHtml();
?>
<?php  if ($blockHtml) { ?>
    <?= $blockHtml ?>
<?php } ?>
<script>
require(['jquery'], function($){
    var storage = window.localStorage.getItem('arteriors_mage');
    var objStorage = $.parseJSON(storage);
    var artData = objStorage['ArtCustomerData'];
    var showUrl = artData['show_url'];
    var klevuData = window.localStorage.getItem('klv_mage');
    var klvobjStorage = $.parseJSON(klevuData);
    var klvData = klvobjStorage['customerData'];
    if (typeof klvData['customer_group_id'] !== "undefined") {
        $('.menu-items').removeClass('hide-navigation');
    }
    else if (showUrl !=='no') {
        $('.menu-items').removeClass('hide-navigation');
    }else{
        $('.menu-bottom').addClass('adjust-position');
    }
});
</script>
