<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */

$item = $block->getItem();
$product = $item->getProduct();
$productImage =$block->getImage($block->getProductForThumbnail($item), 'wishlist_thumbnail');
if ($productImage) {
	 $productImage->setProduct($product);
}

?>
<td class="">
<a class="product-image" tabindex="-1" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
    <?= $productImage->toHtml() ?>
</a>
</td>