<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */



/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<td class="">
<h3 class="product-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</h3>
<span class="spansku">Product: </span> <?= $block->escapeHtml($product->getSku()) ?><br>
<textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Please, enter your comments...')) ?>" name="description[<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="product-item-comment" <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>><?= ($block->escapeHtml($item->getDescription())) ?></textarea>


<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        

$portfolio = $objectManager->get("Magento\MultipleWishlist\Block\Customer\Wishlist\Item\Column\Management");
 ?> 
 <div class="item-manage">
  <div class="btn-box">
 	<div class="wishlist-dropdown move split-button">
    <span class="action toggle"
          data-mage-init='{"dropdown":{}}'
          data-trigger-keypress-button="true"
          data-toggle="dropdown"
        <?php if ($portfolio->getDefaultWishlist()->getId() != $portfolio->getCurrentWishlist()->getId()) : ?> data-wishlist-move-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "wishlistId":"<?= $block->escapeHtmlAttr($portfolio->getDefaultWishlist()->getId()) ?>"}'<?php endif;?>>
        <span><?= $block->escapeHtml(__('Move To Portfolio')) ?></span>
    </span>
     <ul class="items dropdown" data-target="dropdown">
        <?php foreach ($portfolio->getWishlists() as $wishlist) : ?>
            <?php if ($wishlist->getId() !== $portfolio->getWishlistInstance()->getId()) : ?>
                <li class="item">
                    <span role="button"
                          tabindex="0"
                          data-action-keypress="true"
                          data-wishlist-move-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "wishlistId":"<?= $block->escapeHtmlAttr($wishlist->getId()) ?>"}'>
                        <?= $block->escapeHtml($wishlist->getName()) ?>
                    </span>
                </li>
            <?php endif;?>
        <?php endforeach;?>
        <?php if ($portfolio->canCreateWishlists($portfolio->getWishlists())) : ?>
            <li class="item new">
                <span role="button"
                      tabindex="0"
                      class="action new"
                      data-action-keypress="true"
                      data-wishlist-move-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "new":true}'>
                    <span><?= $block->escapeHtml(__('Create New Portfolio')) ?></span>
                </span>
            </li>
        <?php endif;?>
    </ul>
   
</div>
</div>
<div class="btn-box">
<div class="wishlist-dropdown copy split-button">
    <span class="action toggle"
          data-mage-init='{"dropdown":{}}'
          data-trigger-keypress-button="true"
          data-toggle="dropdown"
        <?php if ($portfolio->getDefaultWishlist()->getId() != $portfolio->getCurrentWishlist()->getId()) : ?> data-wishlist-copy-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "wishlistId":"<?= $block->escapeHtmlAttr($portfolio->getDefaultWishlist()->getId()) ?>"}'<?php endif;?>>
        <span><?= $block->escapeHtml(__('Copy To Portfolio')) ?></span>
    </span>
    <ul class="items dropdown" data-target="dropdown">
        <?php foreach ($portfolio->getWishlists() as $wishlist) : ?>
            <?php if ($wishlist->getId() !== $portfolio->getWishlistInstance()->getId()) : ?>
                <li class="item">
                    <span role="button"
                          tabindex="0"
                          data-action-keypress="true"
                          data-wishlist-copy-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "wishlistId":"<?= $block->escapeHtmlAttr($wishlist->getId()) ?>"}'
                          title="<?= $block->escapeHtml($wishlist->getName()) ?>">
                        <?= $block->escapeHtml($wishlist->getName()) ?>
                    </span>
                </li>
            <?php endif; ?>
        <?php endforeach;?>
        <?php if ($portfolio->canCreateWishlists($portfolio->getWishlists())) : ?>
            <li class="item new">
                <span role="button"
                      tabindex="0"
                      class="action new"
                      data-action-keypress="true"
                      data-wishlist-copy-item='{"itemId":"<?= $block->escapeHtmlAttr($item->getId()) ?>", "new":true}'>
                    <span><?= $block->escapeHtml(__('Create New Portfolio')) ?></span>
                </span>
            </li>
        <?php endif;?>
    </ul>
</div>
</div>
<?php echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Customer\Wishlist\Button")->setTemplate("Magento_Wishlist::button/update.phtml")->toHtml(); ?> 
 </div>
 


</td>


