<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);
$requiredAttributesPrechecked = $block->getData('required_attributes_prechecked');

$consumerHelper = $this->helper('\Ntz\BillingAddress\Helper\ConsumerHelper');
?>
<div class="container-fluid">
<div class="col-sm-12 col-lg-12">
<form class="form-address-edit" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <h2 class="legend"><?= $block->escapeHtml(__('Contact Information')) ?></h2>
        
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
        <?= $block->getNameBlockHtml() ?>
        <?php if ($addressHelper->isAttributeVisible('company') && !$consumerHelper->isConsumer()) : ?>
        <div class="field company <?php if (in_array('company', $requiredAttributesPrechecked)) :
            ?>required<?php endif; ?>">
            <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="<?= $block->escapeHtml(__('Company')) ?>" value="<?= $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('company')) ?>" />
            </div>
        </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-6">
                <?php if ($addressHelper->isAttributeVisible('telephone')) : ?>
                    <div class="field telephone required ?>">
                    <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
                    <div class="control">
                        <input type="text" name="telephone" value="<?= $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtml(__('Telephone')) ?>" class="input-text v-validate us-phone-validate required-entry" id="telephone" data-validate="{required:true,'validate-length':true}" maxlength="20"/>
                    </div>
                    <div class="phone-note">(Please enter only numeric values eg. 1912345678)</div>
                </div>
                <?php endif; ?>
            </div>
            <div class="col-md-6">
                <div class="field fax">
                    <label class="label" for="fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
                    <div class="control">
                        <input type="text" name="fax" id="fax" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" value="<?= $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('fax')  ?>" data-validate="{ 'validate-number':true}"/>
                    </div>
                    <div class="phone-note">(Please enter only numeric values eg. 1912345678)</div>
                </div>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <h2 class="legend"><?= $block->escapeHtml(__('Address')) ?></h2>
        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field street required wide">
            <label for="street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
            <div class="control">
                <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" maxlength="49" />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++) : ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getStreetLine($_i)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" maxlength="49" />
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

    <div class="row">
        <div class="col-md-6">
       
		
		<div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
       </div>
       <div class="  col-md-6">
        <div class="field region required">
            <label class="label" for="region_id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>"  title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
    </div>
    </div>
    <div class="  row">
         <div class=" col-md-6">
         <div class="field city required ">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city') ?>" id="city"/>
            </div>
        </div>
    </div>
		<div class=" col-md-6">
        <div class="field zip required">
            <label class="label" for="zip"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" value="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= /* @noEscape */ $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')  ?>" data-validate="{'required':true, 'validate-zip-international':true}" />
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
    </div>
       
</div>

        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_address_user_attributes'); ?>
        <?php if ($userDefinedAttributes) :?>
            <?= $userDefinedAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif;?>
<?php if ($block->isDefaultShipping()){  ?>
            <div class="address-message">
                <!-- <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox"/>  -->
                 <strong><?= $block->escapeHtml(__("Default Shipping Address")) ?></strong>
            </div>
        <?php } else{ ?>
            <div class="address-message">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox"/> 
                 <strong><?= $block->escapeHtml(__("Use as my default shipping address")) ?></strong>
            </div>
        <?php } ?>


            
    </fieldset>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <p class="back-link"><a href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><small>« </small><?= $block->escapeHtml(__('Back')) ?></a></p>
        <button data-action="save-address" type="submit" title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>" class="button"><span><span><?= $block->escapeHtml(__('Save Address')) ?></span></span></button>
    </div>
</form>
</div>
</div>
<style type="text/css">
  label.label,
  .label{
    font-weight: 400!important;
  }
</style>
<script type="text/x-magento-init">
    { ".v-validate": { "Ntz_CustomerLogin/js/ntz_validation": {} } }
</script>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
