<div style="width:100%;margin:auto;clear:both;padding:15px;">
    <div class="candid-banner-title candid-banner-title-home">#ARTERIORSHOME — INSPIRED BY YOU</div>
    <div class="view-gallery"><a href="<?php echo $this->getUrl('inspiration');?>" title="VIEW GALLERY">VIEW GALLERY</a></div>
    <!-- BEGIN: Candid Widget -->
	<div style="text-align:center">
		<script src="//api.getcandid.com/scripts/widget.js"></script>
		<script type="text/javascript">
			candid.init({
				id: '2509528b-e2a9-40f4-848f-f6f0099ef7af',
				tag: 'guest_designer',
				theme: 'ct-basic',
				overlayTheme: 'ct-basic',
				cluster: 'prod-3',
				margin: 10,
				width: 200
			});
		</script>
	</div>
	<!-- END: Candid Widget -->
</div>
