<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>
<?php 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $objectManager->get('Magento\Customer\Model\Session');
            $customer_id = $customerSession->getCustomer()->getGroupId();
            $id = "";
            if($customer_id != "86"):
            ?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()) : ?>
    <button type="button" data-role="all-tocart" title="<?= $block->escapeHtmlAttr(__('Add All to Cart')) ?>" class="button btn-share">
        <span><?= $block->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
<?php endif;?>
<?php endif; ?>