<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Button $block */
?>


<?php if ($block->getWishlist()->getItemsCount()) : ?>
    <button type="submit" name="do" title="<?= $block->escapeHtmlAttr(__('Update Portfolio')) ?>" class="button btn-update">
        <span><?= $block->escapeHtml(__('UPDATE PORTFOLIO')) ?></span>
    </button>
<?php endif;?>
