<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<?php

$productId = (int)$block->getRequest()->getParam('product');

if ($productId):
    $product = $block->getProductById($productId);
    ?>
    <h1><?= $block->escapeHtml($product->getName()); ?><?= $block->escapeHtml(__(' can be found at the following stores:&nbsp;')); ?></h1>
    <hr>
<?php endif; ?>
<div class="amlocator-main-container" style="<?= $block->escapeHtml($block->getMainBlockStyles()); ?>">
    <?php if ($block->getWidgetDescription()): ?>
        <div>
            <strong><?= $block->escapeHtml($block->getWidgetDescription()); ?></strong>
        </div>
    <?php endif; ?>

    <div class="amlocator-map-container" id="<?= $block->escapeHtml($block->getMapContainerId()); ?>">
	
	<div class="row">
		<div class="col-xs-12 col-md-12 col-lg-12">
			<h1> Find Us</h1>
			<p>Immerse yourself in a reimagined vision of luxury and experience our extraordinary collections at any of our Retail Partners or Showrooms. </p>
		</div>
	</div>
	
	<section>
		<div class="row">
			<div class="col-xs-12 col-md-12 col-lg-12">
				<div class="first">
					<div class="amlocator-block -map">
					<div class="amlocator-map" id="<?= $block->escapeHtml($block->getMapId()); ?>"></div>
					<?php if ($block->getShowSearch()): ?>
						<div class="amlocator-search-container">
							<div class="amlocator-block -current amlocator-current-location">
								<div class="amlocator-wrapper">
									<input type="text" value="" class="amlocator-text"
										   name="address" placeholder="<?= $block->escapeHtml(__('Enter City, State or Zip')); ?>"
										   data-amlocator-js="address"
										   autocomplete="off">
									<span class="amlocator-search" data-amlocator-js="search">SEARCH</span>
									<span class="amlocator-reset -hidden" data-amlocator-js="reset"></span>
								</div>
							</div>
						 
							<div class="amlocator-block -separator"><hr class="hr"/></div>
						</div>
					<?php endif; ?>
					</div>
				</div>
				
				<div class=" ">
                            <?php if ($block->getShowLocations()): ?>
            
               <div class="title-list amloctor-title-list " style="display: none;">
                <div class="head1 head2" id="reusltp">RESULTS</div>
                    <div class="content" >
        
                         <div class="content-on-null" > <b> Arteriors Stores Near <span id="search-value"></span></b>: Found <span id="counter-map"></span>
                                <?php foreach ($block->getSearchRadius() as $range): ?>
                                    <?php if((int)$range==50): ?>
                                        <span class="miles-text"> within 50 miles. </span>
                                    <input  class="amlocator-select" id='miles50' data-amlocator-js="radius-select"  type="hidden" value="<?= is_numeric($range) ? (int)$range : ''; ?>" name="radius">
                                    <?php elseif((int)$range==100): ?>
                                        <a class="serachbyradius" href="javascript:void(0)">Search for stores within 100 miles? </a>
                                        <input class="amlocator-select" id='miles100' data-amlocator-js="radius-select"  type="hidden" value="<?= is_numeric($range) ? (int)$range : ''; ?>" name="radius">
                                    <?php else: ?>
                                        <input class="amlocator-select" data-amlocator-js="radius-select" disabled="disabled"  type="hidden" value="<?= is_numeric($range) ? (int)$range : ''; ?>" name="radius">
                                    <?php endif; ?>
                                     
                                <?php endforeach;?>
                         </div>

                    </div>
                    <?php if ($attributes = $block->getAttributes()): ?>
                <div class="amlocator-block -filter">
                    <div class="amlocator-filters-container">
                        <div id = "<?= $block->escapeHtml($block->getFiltersId()); ?>"
                         class="amlocator-title"
                         data-amlocator-js="filters-title">
                           
                        </div>
                        <!-- <div class="amlocator-content<?= $block->escapeHtml($block->getFilterClass()); ?>"
                             data-amlocator-js="filters-container"> -->
                         <div class="amlocator-content .amlocator-main-container .amlocator-filters-container"
                             data-amlocator-js="filters-container">
                            <?php $attributes = $block->getAttributes();?>
                            <form class="attributes" action="#" data-amlocator-js="attributes-form">
                                <?php foreach ($attributes as $attribute): ?>
                                    <?php if ((int)$attribute['attribute_id']==1) { ?>
                                     
                                    <div class="amlocator-attribute-wrapper">

                                        <div class="amlocator-label">View :</div>
                                        <div class="amlocator-input">
                                        <div class="view-all">
                                        <input type="radio" name="<?= (int)$attribute['attribute_id'];?>" class="amlocator-select none-platinum-store" value="" >
                                        <span class="label-radio">All Stores</span> 
                                    
                                          <input type="radio" name="<?= (int)$attribute['attribute_id'];?>" class="amlocator-select platinum-store" value="1" >
                                          <span class="label-radio">Arterior’s Showrooms</span>
                                          </div>
                                        </div>
                                    </div>
                                       
                               <?php     } ?>
                                <?php endforeach;?>
                            </form>
                            <div class="amlocator-actions" style="display: none;">
                                <span class="amlocator-clear"
                                   title="<?= $block->escapeHtml(__('Reset')); ?>"
                                   data-amlocator-js="clear-filters">
                                    <?= $block->escapeHtml(__('Reset')); ?>
                                </span>
                                <button class="amlocator-button amlocator-filter-attribute platinum-user-button"
                                        title="<?= $block->escapeHtml(__('Filter')) ?>">
                                    <?= $block->escapeHtml(__('Filter')); ?>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
                </div>
                <a style="display: none;" class="amlocator-button nearby-button "
                        title="<?= $block->escapeHtml(__('Locate Nearby')); ?>">
                    <?= $block->escapeHtml(__('Locate Nearby')); ?>
                </a>
               
                <div class="amlocator-block amlocator-store-list" style="display: none;">
                    
                    <?= $block->getLeftBlockHtml(); ?>
                </div>
         </div>
                

        <?php endif; ?>
				
			</div>
		</div>
		
	</section>
	
     
         
        
    </div>
 </div>
</div>

<script>
    require([
        'jquery',
        'Amasty_Storelocator/js/main',
        'Amasty_Storelocator/js/cluster',
        'domReady!',
        'mage/loader',
        'https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= $block->escapeHtml(
            $block->configProvider->getApiKey()
        ); ?>'
    ], function ($) {
        var mapId =  "<?= '#' . $block->escapeHtml($block->getMapId()); ?>",
            $body = $('body'),
            isLoaderAjaxInitiated = !!$.data($body.get(0), 'mage-loader'),
            isLoaderInitiated = isLoaderAjaxInitiated,
            initFunction,
            tryToInit = function () {
                if (isLoaderInitiated && isLoaderAjaxInitiated) {
                    initFunction();

                    return true;
                }

                return false;
            };

        initFunction = function () {
            $(mapId).amLocator({
                amMediaUrl :"<?= $block->escapeHtml($block->getAmStoreMediaUrl()); ?>",
                mapZoom: <?= $block->escapeHtml($block->getMapZoom()); ?>,
                productId: "<?= (int)$block->getProductId() ?>",
                categoryId: "<?= (int)$block->getCategoryId() ?>",
                automaticLocate: "<?= (bool)$block->getAutomaticLocate(); ?>",
                enableClustering: "<?= (bool)$block->getClustering(); ?>",
                enableSuggestionClickSearch: "<?= (bool)$block->getSuggestionClickSearch(); ?>",
                enableCountingDistance: "<?= (bool)$block->getCountingDistance(); ?>",
                distanceConfig: "<?= $block->escapeHtml($block->getDistanceConfig()); ?>",
                useGeoConfig: "<?= (bool)$block->getGeoUse()?>",
                allowedCountries: <?= /* @noEscape */ $block->getAllowedCountries(); ?>,
                ajaxCallUrl: "<?= $block->escapeHtml(
                    $block->getUrl('amlocator/index/ajax') . $block->getQueryString()
                ); ?>",
                useBrowserLocation: "<?= (bool)$block->getUseBrowserLocation()?>",
                jsonLocations: <?= /* @noEscape */ $block->getJsonLocations() ?>,
                imageLocations: "<?= $block->escapeHtml($block->getViewFileUrl('Amasty_Storelocator::images/')); ?>",
                mapId : "<?= $block->escapeHtml($block->getMapId()); ?>",
                mapContainerId: "<?= $block->escapeHtml($block->getMapContainerId()); ?>",
                showSearch: <?= (int)$block->getShowSearch(); ?>,
                <?php if ($block->getRadiusType() == 'range'):?>
                isRadiusSlider: <?= $block->escapeHtml($block->getRadiusType()) == 'range'?>,
                maxRadiusValue: <?= (int)$block->getMaxRadiusValue(); ?>,
                minRadiusValue: <?= (int)$block->getMinRadiusValue(); ?>,
                measurementRadius: "<?= ($block->getDistanceConfig() != 'choose') ?
                    $block->escapeHtml($block->getDistanceLabel()) : ''?>"
                <?php endif;?>
            });
        };

        tryToInit();
        $body.on('loadercreate', function () {
            isLoaderInitiated = true;
            tryToInit();
        }).on('loaderajaxcreate', function () {
            isLoaderAjaxInitiated = true;
            tryToInit();
        });
        $('.amlocator-search').on('click',function(){
            $('#miles50').val(50);
             $('#miles50').removeAttr('disabled');
             $('#miles100').attr('disabled','disabled');
            $(".nearby-button").click();
             var value = $('.amlocator-text').val();
             $('#search-value').text(value);
            if (value != '') { 
            $('.amlocator-store-list , .amloctor-title-list').show();
            }else{
            alert('Please enter a location to search!');
            $('.amloctor-title-list , .content-on-null').show();
            }

        });
        $('.amlocator-text').on('click',function(){
           if ($(".amlocator-search").hasClass('-hidden')) {
            $(".amlocator-search").removeClass('-hidden');
            $(".amlocator-reset").addClass('-hidden');
           }
        });
        $('.serachbyradius').on('click',function(){
            $('#miles50').val(100);
            $('#miles100').removeAttr('disabled'); 
            $('#miles50').attr('disabled','disabled');
           $(".nearby-button").click();
           $(".platinum-user-button").click();
        });
        $('.platinum-store').on('click',function(){
           $(".platinum-user-button").click()
        });
        $('.none-platinum-store').on('click',function(){
           $(".platinum-user-button").click()
        });
    });
</script>
