<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */




?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="container m2 checkout-success">
    <?php if ($block->getOrderId()) :?>
        <div class="page-title col-sm-12">
        <h1>Your order has been received.</h1>
        </div>
        <h2 class="sub-title col-sm-12">Thank you for your purchase!</h2>
        <div class="col-sm-12 success-messages">
            <?php if ($block->getCanViewOrder()) :?>
                <p><?= $block->escapeHtml(__('Your order # is: Web Id')) ?>
                    <span>
                            <?= /* @noEscape */$block->getOrderId() ?>
                     </span> 
                </p>
            <?php  else : ?>
                <p>
                    <?= $block->escapeHtml(__('Your order # is: Web Id')) ?>
                    <span>
                        <?= /* @noEscape */$block->getOrderId() ?>
                    </span>
                </p>
            <?php endif;?>
            <p><?= $block->escapeHtml(__('You will receive an order confirmation email with details of your order and a link to track its progress.')) ?></p>
            <p>
            Click <a href="<?= $block->getViewOrderUrl() ?>" target="_blank">here to print</a> a copy of your order confirmation. 
            </p>
            <div class="actions-toolbar">
            <div class="primary">
                <a class="action primary continue" href="<?= /* @noEscape */$block->getUrl() ?>">
                    <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
                </a>
            </div>
            </div>
        </div>
        
    <?php endif;?>

</div>


 
