<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?> 
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */


?>
<?php
$count = 0;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$customHelper = $this->helper('Ntz\Productpage\Helper\Data');
// $configHelper = $this->helper('Ntz\Instock\Helper\Backorderz');
// $valueData  =     $configHelper->getConfig('cataloginventory/item_options/backorders');



$routeName = $this->getRequest()->getRouteName();
$groupname = $customHelper->getCustomerGroupName(); //$block->getCustomerGroupName();
$canShowPrice = $customHelper->getCanShowPrice(); // $block->getCanShowPrice();
$canAddToCart = $customHelper->getCanAddToCart();
$canAddToPortfolio = $customHelper->getCanAddToPortfolio();

if($routeName != 'catalogsearch') {
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    $getCategoryInfo = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
    $arrCount = "";
    if ($getCategoryInfo->getMpNewAttribute()){
        $staticBlockIdentifierForAds = str_replace(' ', '', $getCategoryInfo->getMpNewAttribute());
        $staticBlockIdentifierForAdsArr = explode("," ,$staticBlockIdentifierForAds);
        //echo '<pre>'; print_r($staticBlockIdentifierForAdsArr); echo '</pre>';
        $arrCount = count($staticBlockIdentifierForAdsArr);
    }

}    


$imageAltText = $customHelper->getCustomVariableValue('image_alt_txt'); 
$imageAltTextArray =  json_decode($imageAltText,true);



$new_category_id = $customHelper->getCustomVariableValue('new_category_id'); //$block->getCustomVariableValue('new_category_id');
$essential_lighting_category_id = $customHelper->getCustomVariableValue('essential_lighting_category_id') ; //$block->getCustomVariableValue('essential_lighting_category_id');
$guest_designer_cat_id = $customHelper->getCustomVariableValue('guest_designer_cat_id') ; 

 $guest_designer_cat_id=  json_decode($guest_designer_cat_id,true);
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

$request = $objectManager->get('Magento\Framework\App\Request\Http');
$layout = $request->getFullActionName();
?>

<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?php //$block->getToolbarHtml() ?>
    <?php
    $tool_block = $this->getLayout()->createBlock("Magento\Catalog\Block\Product\ProductList\Toolbar");
    $tool_block->setCollection($_productCollection);
    //$tool_block->setPosition('top');
    echo $tool_block->setTemplate("Magento_Catalog::product/list/toolbar-top.phtml")->toHtml(); ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $pageNumber = (int)$this->getRequest()->getParam('p', 1); //$this->getRequest()->getParam('p');
    ?>
    
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <?php if($routeName != 'catalogsearch') { ?>
            <?php if($getCategoryInfo->getPageLayout() == 'category-layout-with-1ad') { ?>
                <?php if($pageNumber <= $arrCount ) { ?>
                    <ul class="grid-container products-grid .products .list .items .product-items">
                <?php } else { ?>
                     <ul class="cust-grid products-grid .products .list .items .product-items">
                <?php } ?>            
            <?php } elseif($getCategoryInfo->getPageLayout() == 'category-layout-with-2ads') { ?>
                <?php if($pageNumber <= ($arrCount/2) ) { ?>
                    <ul class="grid-container-2 products-grid .products .list .items .product-items">
                <?php } else { ?>
                     <ul class="products-grid .products .list .items .product-items">
                <?php } ?>  
            <?php } else { ?>
                <ul class="products-grid .products .list .items .product-items">
            <?php } ?> 
        <?php } else { ?>
            <ul class="products-grid .products .list .items .product-items">
        <?php } ?>        


        <?php /*<ul class=" && $pageNumber == 1) { echo "grid-container"; } ?> <?php if($getCategoryInfo->getPageLayout() == 'category-layout-with-2ads') { echo "grid-container-2"; } ?> products-grid .products .list .items .product-items"><?php */ ?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
            $className="product_number";
            $product_counter = 0;
            $products_count = count($_productCollection);
            foreach ($_productCollection as $_product): 
				$count = $count+1;
                $product_counter++;
                $categoryIds = $_product->getCategoryIds();
                if($_product->getTypeId() == 'configurable'){
                    $product_id = $_product->getId();
                    $configProduct = $customHelper->getCustomProductLoad($product_id); //$block->getCustomProductLoad($product_id);                 
                    $_children = $configProduct->getTypeInstance()->getUsedProducts($configProduct);
					
                    foreach ($_children as $child){
                        $_product = $customHelper->getCustomProductLoad($child->getID()); //$block->getCustomProductLoad($child->getID());  
                    }
                }

                //alt text for image
                $altText = $_product->getSku().' '.$_product->getName();
                ?>
                <?php if($routeName != 'catalogsearch') { ?>
                <?php $countCheck = '';
                if ($arrCount){
                    $countCheck = $arrCount/2;
                }
                ?>
                    <?php if($pageNumber <= $countCheck) { ?>
                        <?php if($count == 1 && $getCategoryInfo->getPageLayout() == 'category-layout-with-2ads') { ?>
                            <li>
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($staticBlockIdentifierForAdsArr[($pageNumber-1)*2])->toHtml(); ?>
                            </li>
                        <?php } ?>

                        <?php if($count == 14 && $getCategoryInfo->getPageLayout() == 'category-layout-with-2ads') { ?>
                            <li>
                                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($staticBlockIdentifierForAdsArr[(($pageNumber-1)*2)+1])->toHtml(); ?>
                            </li>
                        <?php } ?>
                    <?php } ?>    
                <?php } ?>    
                
                <li class="item .product .product-item <?php echo "product-number".$_product->getId(); ?>">
                    <div class=".product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                         $productImage->setProduct($_product);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'. 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class=".product photo product-item-photo"
                           tabindex="-1" title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">    
                            <?php $rehoverImage=$_product->getData('slider_images');?>
                            <?php
                            if($rehoverImage) {
                                $rehoverImage = (explode(",", $rehoverImage));
                                $count_images = count($rehoverImage);
                            }

                            $cnt = 1; 
                            if (empty($rehoverImage[0])):
                            $cnt = 0;
                            endif; 
                            ?>

                                    <div class="product-image image<?php echo$_product->getId(); ?>"> 
                                    <div class="owl-carousel">
                                        <?= $productImage->toHtml(); ?>
                                        <?php if($cnt != 0): ?> 
                                         
                                        <?php
                                        for($i=0;$i<=$count_images-1;$i++)
                                        {
                                        ?>
                                         <?php
                                        $altText1='';
                                        $filename=[];
                                        $fileParts = pathinfo($rehoverImage[$i]); 
                                        if (isset($fileParts['filename'])) {
                                         $filename=   explode('.', $fileParts['filename']);
                                          if(isset($filename[1]) && isset($imageAltTextArray[$filename[1]])){
                                                $altText1=   $imageAltTextArray[$filename[1]];
                                            }
                                        }
                                        ?>
                                                <img src="<?php echo$rehoverImage[$i];?>" alt="<?php echo  $altText.' '.$altText1 ?>">
                                        <?php } ?>
                                    <?php endif; ?>
                                    </div>
                                    </div>
                         
                            <div class="product-bottom .product .details .product-item-details">
                                <div class="left-information">
                                    <?php if($routeName!='catalogsearch'): ?>
                                        <?php if(!in_array($new_category_id, $categoryIds)): 
                                            $stock = $customHelper->getCustomStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
                                             $valueData = $customHelper->getBackorders($_product->getId());
                                              
                                            if($stock <= 3  && $stock > 0 && $valueData == 0 ): ?>
                                                <div class="special-product">
                                                    <?php echo __('Last Chance | Select Few Available') ?>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if(in_array($essential_lighting_category_id, $categoryIds)): ?>
                                            <div class="special-product">
                                                <?php echo __('Essential Lighting') ?>
                                            </div>
                                    <?php endif; ?>
                                    <?php if(in_array($new_category_id, $categoryIds)){ ?>
                                            <div class="special-product">
                                                <?php echo __('New') ?>
                                            </div>
                                    <?php }else{ ?>
                                        <?php foreach ($guest_designer_cat_id as $key => $gdCatId) {
                                          
                                          if(in_array($key, $categoryIds)): ?>
                                                <div class="special-product">
                                                    <?php echo __($gdCatId) ?>
                                                </div>
                                        <?php endif;
                                        }
                                    }
                                     ?>
                                    <h2 class="product-name"><?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
                                    <span class="product-sku">
                                        <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku'); ?>
                                    </span>
                                    
                                    <?php 
                                    echo $customHelper->getDimensions($_product);
                                    $availability = $_product->getData('custom_stock');
                                    if($availability == ''){
                                        if ($_product->isAvailable()){
                                            $availability = 'In Stock';
                                        }
                                    } ?>
                                    <span class="product-status">
                                        <?php echo $availability; ?>
                                    </span>
                                </div>

                                <div class="right-information">
                                    <div class="price-box" id="product-price-<?php echo $_product->getId(); ?>">
                                        <?php
                                        $msrp = $_helper->productAttribute($_product, $_product->getMsrp(), 'msrp');
                                        $formatMsrp = $customHelper->getCustomMsrp($msrp);
                                        
                                        if (!$customerSession->isLoggedIn() && isset($canShowPrice) && $canShowPrice==true) {
                                            ?>
                                            <p class="sugested-price ">
                                                <span class="price-label"><?= __('MSRP:'); ?></span>
                                                <span class="price"><?= $formatMsrp; ?></span>
                                            </p>
                                            <?php
                                        } elseif ($customerSession->isLoggedIn()) {
                                            $customerGroup = $customHelper->getHidePriceGroup();
                                            $customer = $customerSession->getCustomer();
                                            $customerGroupId = $customer['group_id'];
                                            //$groupname = $objectManager->create('\Magento\Customer\Api\GroupRepositoryInterface')-> getById($customerGroupId)->getCode();
                                            $groupname = $customHelper->getCustomerGroupName();
                                            $group_4ML = array("4MLDNET","4MLNOVAT","4MLRRP","4MLTELT","4MLWHSL");
                                            if(!in_array($customerGroupId, $customerGroup) && !in_array($groupname, $group_4ML)) {
                                                ?>
                                                <p class="sugested-price ">
                                                    <span class="price-label"><?= __('MSRP:'); ?></span>
                                                    <span class="price"><?= $formatMsrp; ?></span>
                                                </p>
                                                <?php
                                            }
                                            if($groupname!="LIST") {
                                                echo $block->getProductPrice($_product);
                                                echo $customHelper->getGroupBasedData();
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </a>

                        <?php if($canAddToCart || $canAddToPortfolio) { ?>
                            <?php
                            $blockPosition = "";
                            if ($pos && $viewMode && strpos($pos, $viewMode . '-actions')){
                                $blockPosition = $block->escapeHtmlAttr($position);
                            }
                            ?>
                        <div class=".product actions .product-item-actions"<?= $blockPosition ?>>
                            <?php if ($_product->isSaleable() && $customerSession->isLoggedIn() && $canAddToCart) : ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form"
                                        data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                        action="<?= $block->escapeUrl($postParams['action']) ?>"
                                        method="post">
                                        <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <p>
                                            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart .primary button btn-cart">
                                                <i class="icon-arrows-square_plus"></i>
                                            </button>
                                        </p>
                                    </form>
                            <?php else : ?>
                                <?php /*if ($_product->isAvailable()) :?>
                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                <?php else :?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                <?php endif;*/ ?>
                            <?php endif; ?>

                            <?php
                                if ($canAddToPortfolio && $addToBlock = $block->getChildBlock('addto')) :?>
                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                            <?php endif; ?>
                        </div>
                        <?php } ?>
                    </div>
                </li>

                <?php if($routeName != 'catalogsearch') { ?>
                    <?php if($pageNumber <= $arrCount) { ?>
        				<?php if($count == 1 && $getCategoryInfo->getPageLayout() == 'category-layout-with-1ad') { ?>
        					<li>
                                <?php //print_r($pageNumber); ?>    
            					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($staticBlockIdentifierForAdsArr[$pageNumber -1])->toHtml(); ?>
        					</li>
        				<?php } ?>
                    <?php } ?> 
                <?php } ?>    

                <?php $proId = $_product->getId(); ?>
                <script type="text/javascript">
                require([
                    'jquery',
                    'domReady!'// wait for dom ready
                ], function ($) {
                     var proId = '<?php echo $proId ; ?>';     
                   if ($('div.strikenew'+proId).length){
                        $('.price-final_price #product-price-'+ proId ).addClass('strikthrough');
                    }
                    
                });
                </script>
            <?php endforeach; ?>
        </ul>
		
    </div>
    <div id="loader-icon"></div>
    <a href="#" id="back-to-top" title="Back to top">&uarr;</a>
    <?php //$block->getToolbarHtml() ?>
    <?php echo $tool_block->setTemplate("Magento_Catalog::product/list/toolbar-bottom.phtml")->toHtml(); ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>


<style>
    div.toolbar-top:not(:first-child) {
    	display: none !important;
    }
    .products-grid .owl-item img{
        width: 420px !important;
        height: 420px !important;
        object-fit: contain;
      /*  object-fit: cover;*/
    }
    .owl-dots.disabled {
    visibility: hidden!imortant;
    display: block !important;
    }
    .product-item-photo .product-image img{
        width: 100%!important;
        height: 100%!!important;
    }


    /*******New Layout Style********/
    .grid-container {
      display: grid;
      grid-template-columns: 25% 25% 25% 25%;
      list-style: none;
    }
    .grid-container > li {
      width: auto!important;
    }
    .grid-container li:nth-child(2){
      grid-area: 1 / 2 / 3 / 4;
    }
    .products-grid .item a .product-bottom {
        height: 147px;
    }
	
	
	.grid-container-2 {
	  display: grid;
	  grid-template-columns: 25% 25% 25% 25%;
	  list-style: none;
	}
	.grid-container-2 > li {
	  width: auto!important;
	}

	.grid-container-2 li:nth-child(1){
	  grid-area: 1 / 1 / 1 / 3;
	}

	.grid-container-2 li:nth-child(28){
	  grid-area: 4 / 3 / 4 / 5;
	}
	

	

    @media only screen and (min-width: 320px) and (max-width: 767px) {
    	.grid-container {
    		grid-template-columns: auto;
    	}
    	.grid-container li:nth-child(2){	
    	  grid-row: 1 / 2;
    	  grid-column: 1 / 1;
    	
    	}
    	.grid-container > li {
    		max-width: 376px;
    	}
		.grid-container-2 {
			grid-template-columns: auto;
		}
		
		.grid-container-2 > li {
    		max-width: 376px;
    	}
		
		.grid-container-2 li:nth-child(1){	
		  grid-row: 1 / 1;
		  grid-column: 1 / 1;
		  min-height: 400px;
		line-height: 400px;
		}
		.grid-container-2 li:nth-child(28){
			grid-row: 15 / 15;
			grid-column: 1 / 1;
			min-height: 400px;
			line-height: 400px;
		}
		.category-page .category-list li, .category-page .products-grid li {
			width: 100%;
		}
    }
    @media only screen and (min-width: 768px) and (max-width: 1366px) {
    	.grid-container {
    		grid-template-columns: 50% 50%;
    	}
    	.grid-container li:nth-child(2){	
    	  grid-row: 2 / 4;
    	  grid-column: 1 / 4;
    	}
    	.grid-container > li {
    		max-width: 376px!important;
    	}
        .grid-container-2 > li {
            max-width: 376px!important;
        }
		.grid-container-2 {
			grid-template-columns: 50% 50%;
		}
		.grid-container-2 li:nth-child(1){	
		  grid-row: 1 / 1;
		  grid-column: 1 / 4;
		  max-width: 100%!important;
		}
		.grid-container-2 li:nth-child(28){
			grid-row: 5 / 5;
			grid-column: 1 / 4;
			max-width: 100%!important;
		}
		.category-page .category-list li, .category-page .products-grid li {
			width: 50%;
		}

    }
	/*@media only screen and (min-width: 1024px) and (max-width: 1366px) {
    	.grid-container {
    		grid-template-columns: 33% 33% 33%;
    	}
    	.grid-container li:nth-child(2){	
    	  grid-row: 2 / 4;
    	  grid-column: 1 / 4;
    	}
    	.grid-container > li {
    		
    	}
		.grid-container-2 {
			grid-template-columns: 33% 33% 33%;
		}
		.grid-container-2 li:nth-child(1){	
		  grid-row: 1 / 1;
		  grid-column: 1 / 4;
		  max-width: 100%!important;
		}
		.grid-container-2 li:nth-child(28){
			grid-row: 5 / 5;
			grid-column: 1 / 4;
			max-width: 100%!important;
		}
		.category-page .category-list li, .category-page .products-grid li {
			width: 33%;
		}
    }*/
	@media screen and (max-device-width: 767px) and (orientation: landscape) {
    .grid-container-2 {
        grid-template-columns: 50% 50%;
    }
}

.category-products .toolbar-top .sorter .sort-by select + .hide-sorter {
    display: none;
}
    
</style>


<?php if ($block->getRequest()->getFullActionName() == 'catalogsearch_result_index') { ?>
    <script type="text/javascript">
    require([
        'jquery',
        'domReady!'// wait for dom ready
    ], function ($) {
         var conceptName = $('.sorter-options').find(":selected").val();    
       if (conceptName!='personalized'){
       
            $('.sort-by-switcher').addClass('hide-sorter');
        }
        
    });
</script>  

   
<?php  } ?>
 <script type="text/javascript">
    require([
        'jquery',
        'domReady!'// wait for dom ready
    ], function ($) {
         var conceptName = $('.sorter-options').find(":selected").val();    
       if (conceptName=='best_sellers'){
       
            $('.sort-by-switcher').addClass('hide-sorter');
        }
        if (conceptName=='most_viewed'){
       
            $('.sort-by-switcher').addClass('hide-sorter');
        }
        
    });
</script>


                           <script type="text/javascript">
                                            require([
                                                'jquery',
                                                'owlcarousel'
                                         ], function ($) {

                                                var owl;
                                                $(document).ready(function() {
                                                    owl = $('.owl-carousel').owlCarousel({
                                                        autoplay:false,           
                                                        items:1,
                                                        dots:true,
                                                        mouseDrag:true, 
                                                        slideBy:1,
                                                        responsiveClass: true,
                                                        responsive:{
                                                            0:{
                                                                dots:true,
                                                            },
                                                            375:{
                                                                    dots:true,
                                                                    mouseDrag:true, 
                                                                    responsiveClass: true,
                                                                    slideBy:1,
                                                                },
                                                                768:{
                                                                    dots:true,
                                                                    responsiveClass: true,
                                                                    mouseDrag:true,
                                                                    slideBy:1,
                                                                },
                                                                1000:{
                                                                    dots:true,
                                                                    responsiveClass: true,
                                                                    mouseDrag: false,
                                                                    slideBy:1,
                                                                    
                                                                  
                                                                }
                                                                
                                                            }

                                                 
                                                    });
                                                    $("li").hover(function(){
                                                    
                                                    }, function(){
                                                    owl.trigger('to.owl.carousel', [0, 400]);
                                                  });
                                                    $('.owl-carousel .owl-dots .owl-dot').hover(function() {
                                                        $(this).click();
                                                    });
                                                });

                                                

                                              });  

                            </script>